# Generated by Django 5.0.3 on 2024-03-15 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DistrictData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district_name", models.CharField(max_length=10)),
                ("large_b1_rent", models.FloatField()),
                ("large_1_rent", models.FloatField()),
                ("large_2_rent", models.FloatField()),
                ("large_3_rent", models.FloatField()),
                ("large_4_rent", models.FloatField()),
                ("large_5_rent", models.FloatField()),
                ("large_6to10_rent", models.FloatField()),
                ("small_b1_rent", models.FloatField()),
                ("small_1_rent", models.FloatField()),
                ("small_2_rent", models.FloatField()),
                ("district_size", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="EmpData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borough", models.CharField(max_length=20)),
                ("mtolfirstfloor", models.FloatField()),
                ("smallfirstfloor", models.FloatField()),
                ("empdensity", models.FloatField()),
                ("emptopopul", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_count", models.IntegerField()),
                ("company_count", models.IntegerField()),
                ("employee_density", models.FloatField()),
                ("company_density", models.FloatField()),
                ("population_density", models.FloatField()),
                ("employee_ratio", models.FloatField()),
                (
                    "district_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis_data.districtdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FloatPopData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subway_in", models.IntegerField()),
                ("subway_out", models.IntegerField()),
                ("bus_in", models.IntegerField()),
                ("bus_out", models.IntegerField()),
                ("subway_in_ratio", models.FloatField()),
                ("subway_out_ratio", models.FloatField()),
                ("bus_in_ratio", models.FloatField()),
                ("bus_out_ratio", models.FloatField()),
                ("combined_in_ratio", models.FloatField()),
                ("combined_out_ratio", models.FloatField()),
                ("total_ratio", models.FloatField()),
                (
                    "district_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis_data.districtdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeoulPopData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s10", models.IntegerField()),
                ("s20", models.IntegerField()),
                ("s30", models.IntegerField()),
                ("s40", models.IntegerField()),
                ("s50", models.IntegerField()),
                ("s60", models.IntegerField()),
                ("s70", models.IntegerField()),
                ("s80_s90", models.IntegerField()),
                ("total", models.IntegerField()),
                ("ratio_10s", models.FloatField()),
                ("ratio_20s", models.FloatField()),
                ("ratio_30s", models.FloatField()),
                ("ratio_40s", models.FloatField()),
                ("ratio_50s", models.FloatField()),
                ("ratio_60s", models.FloatField()),
                ("ratio_70s", models.FloatField()),
                ("ratio_80s_to_90s", models.FloatField()),
                ("ratio_total", models.FloatField()),
                (
                    "district_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis_data.districtdata",
                    ),
                ),
            ],
        ),
    ]
