# Generated by Django 5.0.3 on 2024-03-17 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis_data", "0003_seoulincomedata"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictAge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district_age", models.FloatField()),
                (
                    "district_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis_data.districtdata",
                    ),
                ),
            ],
        ),
    ]
