# Generated by Django 5.0.3 on 2024-03-17 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis_data", "0004_districtage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DistrictAge",
            new_name="DistrictAgeData",
        ),
    ]
